# Use the node:14-alpine base image
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json file from the local directory to the container
COPY package.json .

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

#HERE you need to put your API key from openweathermap.org 
ENV APPID="YOUR_API_KEY"



# Expose port 9000 for the application to listen on
EXPOSE 9000




# Set the default command to run the application
CMD ["npm", "start"]